#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import csv

OUTPUT = "/Users/oz/Documents/CAS-CEO/creactive-studio/clientes/exponor-outreach/Exponor_Emails_Generados.csv"

CIERRE = "Saludos cordiales,\nOscar Vergara\nCreActive Studio | creactivestudio.agency\nWhatsApp: +56 9 8271 7201"

# Línea de prueba social — dato de industria, va entre solución y CTA
L_SOCIAL = "El 82% de los visitantes de ferias industriales tienen autoridad de compra. Son exactamente los contactos que no se pueden perder en los 5 días siguientes."

L2 = {
    # Problema: urgencia de respuesta rápida en repuestos/partes
    "parts": "La mayoría invierte $15.000+ USD en su stand y sale con tarjetas en papel. Sin seguimiento en las primeras 48 horas, esos contactos se los lleva quien respondió primero.",
    # Problema: volumen de contactos sin proceso de seguimiento
    "services": "Exponor dura tres días. El equipo vuelve con 40 tarjetas y nombres anotados. Sin proceso digital de seguimiento, el 40% de esos contactos no avanza en la semana siguiente.",
    # Problema: demos técnicas sin captura estructurada
    "tech": "Las demos generan interés real. El problema viene después: sin captura estructurada, el 40% de los exhibidores tarda más de 5 días en hacer follow-up — y para entonces el prospecto ya eligió a otro.",
    # Problema: decisión post-feria en EPP/seguridad
    "epp": "En EPP y seguridad, el comprador recorre cinco stands en el mismo pasillo. La decisión no se toma ahí — se toma días después. El 40% de los exhibidores no hace seguimiento a tiempo. Eso es perder el partido en el vestuario.",
    # Problema: ciclo largo en construcción/proyectos
    "constr": "En proyectos mineros, la decisión ocurre semanas después de la feria. El 40% de los exhibidores tarda más de 5 días en hacer follow-up — cuando el jefe de proyecto necesita cotizar, ya no recuerda quién era quién.",
}

L3 = {
    # Solución A: workflow completo, credencial escala, 2-4 semanas
    "a": "Por eso armamos Exponor Lead OS: el visitante escanea un QR en su stand, entra al CRM y recibe seguimiento automático en las primeras horas. Listo en 2-4 semanas, con sus procesos de venta reales adentro.",
    # Solución B: sin Excel, sin tarjetas perdidas
    "b": "Para eso desarrollamos Exponor Lead OS: captura por QR en el stand, CRM configurado para su industria y secuencia automática de seguimiento. El equipo sale de Exponor con un proceso — no con 50 tarjetas y un Excel que nadie actualiza.",
    # Solución C: entregamos funcionando, no un manual
    "c": "Creamos Exponor Lead OS para exactamente esto: captura por QR, pipeline por tipo de lead y seguimiento automático en los días clave post-feria. Entregamos todo funcionando — no un manual de cómo hacerlo.",
}

L4 = {
    "a": "¿Tendría 10 minutos esta semana para mostrarle cómo funciona?",
    "b": "¿Le convendría una llamada breve antes de Exponor?",
    "c": "Faltan pocas semanas para junio. ¿Tiene sentido conversar esta semana?",
    "d": "¿Tendría un par de minutos para conversar sobre esto antes de junio?",
}

def build(empresa, tipo, nombre, asunto, l1, l2k, l3k, l4k):
    if tipo == "personal" and nombre.strip():
        saludo = f"Estimado/a {nombre.strip()},"
    else:
        saludo = f"Estimado equipo de {empresa},"
    cuerpo = f"{saludo}\n\n{l1}\n{L2[l2k]}\n{L3[l3k]}\n{L_SOCIAL}\n{L4[l4k]}\n\n{CIERRE}"
    return {"asunto": asunto, "cuerpo_completo": cuerpo}

# (empresa, pabellon, stand, email, nombre_contacto, tipo_email, asunto, l1, l2k, l3k, l4k)
ROWS = [
# ── LOTE 1 ──────────────────────────────────────────────────────────────────
("AMTC - U. de Chile","Pabellón Litio","883","contacto@amtc.cl","","ventas",
 "Exponor 2026: ¿cómo captura leads el AMTC?",
 "El AMTC lidera la investigación tecnológica aplicada a la minería desde la U. de Chile, con proyectos de automatización y procesamiento que interesan directamente a los operadores mineros.",
 "services","a","a"),
("AHK Chile","Pabellón Cobre","47-49","info@ahkchile.cl","","ventas",
 "Cámara Chileno-Alemana: ¿listo para Exponor?",
 "La Cámara Chileno-Alemana conecta a más de 550 empresas y en Exponor 2026 ese rol de puente va a generar conversaciones valiosas con ejecutivos de las grandes mineras.",
 "services","c","b"),
("Almanorte SpA","Pabellón Hierro","1454","contacto@almanortespa.cl","","ventas",
 "Almanorte en Exponor: ¿qué pasa con los leads?",
 "Almanorte es referente en soluciones logísticas integrales en la Región de Tarapacá, atendiendo a la gran minería del norte con más de una década de trayectoria comprobada.",
 "services","b","a"),
("American Parts SpA","Exterior B","46","info@americanparts.cl","","ventas",
 "Exponor 2026: repuestos que no pueden esperar",
 "American Parts importa repuestos originales de motor, inyección y frenos desde USA y Europa, productos que los compradores mineros buscan con urgencia cuando un equipo está detenido.",
 "parts","a","c"),
("Andeslevers SpA","Pabellón Oro","1106","contacto@andeslevers.cl","","ventas",
 "Andeslevers en Exponor: SSO y leads bien capturados",
 "Andeslevers lidera soluciones de Seguridad y Salud Ocupacional para minería, un área donde el comprador toma decisiones basadas en confianza y referencias previas.",
 "epp","b","d"),
("Arquitectura y Construcción Tecno Textil S.A.","Pabellón Oro","1179","asistenteg@arcotex.cl","","generico",
 "Arcotex en Exponor: ventilación y seguimiento digital",
 "Arcotex es experto en sistemas de ventilación para minería y túneles, soluciones críticas donde la relación con el comprador comienza mucho antes de emitir la cotización formal.",
 "services","c","b"),
("Arval Chile","Pabellón Cobre","162","acquisition_cl@arval.cl","","generico",
 "Exponor 2026: ¿Arval tiene su pipeline de leads listo?",
 "Arval, filial de BNP Paribas, asiste a corporaciones con gestión integral de flotas, servicio que conecta directamente con las necesidades de movilidad de las grandes mineras en expansión.",
 "services","a","a"),
("Aspen SpA","Pabellón Oro","1088","contacto@aspenspa.cl","","ventas",
 "Exponor 2026: capturando valor desde el stand de Aspen",
 "Aspen promueve valor y calidad para una minería sustentable, posicionamiento que resuena con los tomadores de decisión que buscan proveedores de largo plazo en Exponor.",
 "services","b","c"),
("Asset Advisors Chile","Pabellón Molibdeno","1240","assetadvisors.cl@gmail.com","Assetadvisors","personal",
 "Exponor genera movimiento inmobiliario — ¿están listos?",
 "Asset Advisors se especializa en asesoría de activos inmobiliarios comerciales, un servicio con demanda natural entre empresas que se instalan o expanden en Antofagasta con la dinámica de Exponor.",
 "services","c","d"),
("Atecmin Ltda.","Pabellón Yodo","742","ventas@atecmin.cl","","ventas",
 "Exponor 2026: señalización y seguimiento de compradores",
 "Atecmin provee señalización de advertencia para minería, vehículos e industria bajo altos estándares de calidad, un producto que siempre tiene compradores urgentes en feria.",
 "parts","a","b"),
# ── LOTE 1 cont. ────────────────────────────────────────────────────────────
("Austin Ingenieros Chile Ltda.","Exterior A","026A","sales@austining.cl","","ventas",
 "Austin Engineering en Exponor: ¿cómo manejan los leads?",
 "Austin Engineering fabrica baldes y estructuras de camión minero en Antofagasta, con presencia en ferias mineras internacionales como fabricante de referencia en ingeniería aplicada.",
 "services","a","a"),
("Austin Ingenieros Chile Ltda.","Exterior A","026A","sales@austineng.co.id","","ventas",
 "Exponor 2026: seguimiento de leads para Austin Engineering",
 "Austin Engineering es fabricante global de baldes y estructuras para camiones mineros, con una operación en Antofagasta que atiende a las mineras más grandes del norte de Chile.",
 "services","c","b"),
("Austin Ingenieros Chile Ltda.","Exterior A","026A","sales@austineng.com.au","","ventas",
 "Austin Ingenieros Chile: Exponor 2026 y pipeline de ventas",
 "Austin Engineering diseña y produce equipos de minería de clase mundial con base local en Antofagasta, siendo un referente técnico que genera conversaciones de alto valor en feria.",
 "services","b","c"),
("BCM Servicios Mineros","Pabellón Yodo","706","ventas@bcmservicios.cl","","ventas",
 "BCM en Exponor: repuestos Epiroc y seguimiento rápido",
 "BCM se especializa en repuestos para equipos Epiroc, Sandvik, Atlas Copco, Normet y Montabert, con software propio para identificación de piezas y referencia cruzada OEM.",
 "parts","b","c"),
("Be Energy Chile","Exterior D","105","contacto@be-energy.cl","","ventas",
 "Be Energy en Exponor: soluciones solares y leads bien gestionados",
 "Be Energy desarrolla soluciones solares móviles para minería: tráilers solares, torres de iluminación, containers solares y plantas móviles para faenas remotas sin conexión a red.",
 "tech","c","d"),
("Bekaert Ropes Chile S.A.","Pabellón Oro","1210","ventas@bekaert.com","","ventas",
 "Bekaert Ropes en Exponor: cuerdas de acero y pipeline activo",
 "Bekaert Ropes, división de Bekaert Bélgica, fabrica cuerdas de acero de precisión para izaje y amarre, soluciones de alto valor técnico para las operaciones más exigentes de la minería.",
 "services","a","a"),
("Bender Chile","Pabellón Cobre","35","administracion@bender-cl.com","","generico",
 "Exponor 2026: ¿Bender tiene su seguimiento digital listo?",
 "Bender Chile ofrece soluciones en seguridad eléctrica: vigilancia del aislamiento, control de corriente diferencial y calidad de red para instalaciones industriales críticas.",
 "tech","b","b"),
("BLUMAQ CHILE S.A.","Pabellón Cobre","188-189","mail@blumaq.com","","generico",
 "Blumaq en Exponor: repuestos Cat/Komatsu y leads activos",
 "Blumaq Chile comercializa repuestos alternativos para Caterpillar, Volvo, Komatsu, Cummins y Case, con presencia global en más de seis regiones del mundo.",
 "parts","a","c"),
("Bombas de Pozo Ltda.","Pabellón Yodo","804","ventas@bombasdepozo.cl","","ventas",
 "Exponor 2026: bombas sumergibles y seguimiento post-stand",
 "Bombas de Pozo tiene más de 30 años en bombas sumergibles y tuberías flexibles, con representación de Wilo y UON para el mercado minero e industrial del norte.",
 "parts","c","d"),
("Bosch Chile","Pabellón Cobre","65","info@cl.bosch.com","","ventas",
 "Bosch en Exponor 2026: tecnología y leads que no se pierden",
 "Bosch Chile trae innovación tecnológica para la industria y minería, con un portafolio que va desde herramientas hasta soluciones de automatización para los proyectos más exigentes.",
 "services","a","a"),
# ── LOTE 2 ──────────────────────────────────────────────────────────────────
("Boyuan Safety Chile","Pabellón Plata","296","vrojas@boyuansafety.cl","","generico",
 "Exponor 2026: EPP Boyuan y compradores que no escapan",
 "Boyuan Safety Chile comercializa elementos de protección industrial incluyendo protectores auditivos de alta atenuación (NRR 30 dB) para los entornos más ruidosos de la minería.",
 "epp","b","b"),
("Bronor Ltda.","Pabellón Litio","965","contacto@bronor.cl","","ventas",
 "Exponor 2026: análisis microbiológicos y seguimiento digital",
 "Bronor presta servicios de análisis microbiológicos de alimentos y aguas para la industria del norte, una función crítica en las faenas donde la salud del personal es prioridad.",
 "services","c","c"),
("Calestarq Seguridad Vial SpA","Pabellón Molibdeno","1309","contacto@calestarq.cl","","ventas",
 "Calestarq en Exponor: seguridad vial y leads calificados",
 "Calestarq se especializa en seguridad vial, un área con demanda creciente en la gran minería por los estándares cada vez más exigentes de gestión de accidentabilidad.",
 "epp","a","d"),
("Calimport S.A.","Exterior E","128","calimport@calimport.cl","","generico",
 "Exponor 2026: ¿Calimport tiene su pipeline de leads?",
 "Calimport atiende a la industria minera y de construcción con suministros y servicios especializados en el norte del país, con trayectoria como proveedor de confianza.",
 "services","b","a"),
("Capelec Capacitaciones & Ing. Eléctrica","Pabellón Litio","894","capelec@capelec.cl","","generico",
 "Capelec en Exponor: capacitaciones eléctricas y más alumnos",
 "Capelec ofrece capacitación eléctrica especializada y formación actualizada en normativa para profesionales industriales, un servicio con alta demanda en minería.",
 "services","c","b"),
("Carval Ltda.","Pabellón Litio","828","antofagasta@carval.cl","","generico",
 "Exponor 2026: mantenimiento industrial y seguimiento digital",
 "Carval provee mantenimiento preventivo y correctivo industrial con presencia en Antofagasta, Calama y Santiago, atendiendo a las operaciones mineras del norte con servicio local.",
 "services","a","c"),
("Caudalex SpA","Pabellón Oro","1109","info@caudalex.cl","","ventas",
 "Caudalex en Exponor: sistemas de impulsión y leads activos",
 "Caudalex ofrece la mejor tecnología en condiciones competitivas para proyectos de sistemas de impulsión, conectando con los equipos de operaciones mineras que buscan eficiencia.",
 "tech","b","d"),
("Christensen Comercial S.A.","Exterior D","109","chrisco@christensen.cl","","generico",
 "Christensen en Exponor: herramientas y compradores bien seguidos",
 "Christensen comercializa discos de corte, lija, herramientas diamantadas y equipos industriales, un portafolio amplio que atrae a compradores de múltiples áreas de la minería.",
 "parts","c","a"),
("Cía. Confiabilidad","Pabellón Cobre","201","ventas@confiabilidad.cl","","ventas",
 "Exponor 2026: confiabilidad 4.0 y pipeline bien gestionado",
 "Cía. Confiabilidad provee monitoreo de condiciones, inspección y gestión de activos con tecnología 4.0 e IA, soluciones de alto valor para plantas que buscan reducir paradas no planificadas.",
 "tech","a","b"),
("Cía. Minera Cordillera Chile Scm","Pabellón Oro","1178","contact@cmcordillera.cl","","ventas",
 "Exponor 2026: sal única en el mundo, leads que no se pierden",
 "Cía. Minera Cordillera extrae sal de calidad única desde un área desértica libre de contaminación, un producto diferenciado con aplicaciones industriales y de proceso en la gran minería.",
 "services","b","c"),
("Cibrugg Ltda","Pabellón Cobalto","1426","arriendos@cibrugg.cl","","generico",
 "Cibrugg en Exponor: arriendo de equipos y relaciones duraderas",
 "Cibrugg se dedica al arriendo de equipos y transporte especializado, construyendo relaciones de largo plazo con clientes del norte minero que necesitan equipos confiables y servicio ágil.",
 "services","c","d"),
("CJM MYS SpA","Pabellón Litio","929","rvejar@cjm.cl","","generico",
 "Exponor 2026: instrumentos de medición y seguimiento activo",
 "CJM comercializa instrumentos de medición eléctrica, fotovoltaica y ambiental con soporte técnico en Chile, productos con demanda directa en los nuevos proyectos de energía minera.",
 "tech","a","a"),
("CMS Cepcor Chile SpA","Pabellón Yodo","626","sales@cmscepcor.com","","ventas",
 "CMS Cepcor en Exponor: repuestos para trituradoras y leads activos",
 "CMS Cepcor es el fabricante europeo líder de repuestos aftermarket para trituradoras, cribas y plantas de asfalto, con suministro a más de 120 países.",
 "parts","b","b"),
("CMSERVICES Ingeniería y Servicios","Pabellón Cobre","267","antofagasta@cmservices.cl","","generico",
 "Exponor 2026: torque, tensión y leads bien capturados",
 "CMSERVICES provee soluciones en torque, tensión y levante para equipos mineros desde Antofagasta, especializado en gatas hidráulicas para camiones CAEX.",
 "parts","c","c"),
("Codifil Filtracion Ltda.","Pabellón Plata","625","ventas@codifil.cl","","ventas",
 "Codifil en Exponor: filtración industrial y seguimiento digital",
 "Codifil es líder en manufactura textil industrial para filtración, fabricando filtros para procesos industriales con presencia reconocida en la gran minería chilena.",
 "services","a","d"),
("Comeco Chile","Pabellón Cobalto","1387","mzamorano@comecosac.com","","generico",
 "Comeco en Exponor 2026: ¿cómo capturan sus contactos?",
 "Comeco Chile atiende a la industria con productos técnicos y soluciones de ingeniería, con trayectoria consolidada en el mercado latinoamericano de proveedores mineros.",
 "services","b","a"),
("Comercial Acuario Ltda","Pabellón Molibdeno","1213","ventas@comercialacuario.cl","","ventas",
 "Comercial Acuario en Exponor: faros LED y compradores activos",
 "Comercial Acuario es líder en faros faeneros LED, balizas y corta corrientes para camiones mineros desde 1983, un proveedor que los compradores de mantenimiento reconocen por su trayectoria.",
 "parts","c","b"),
("Comercial de Aceros JG SpA","Pabellón Hierro","1467","ventas@acerosjg.cl","","ventas",
 "Exponor 2026: acero a medida y seguimiento de compradores",
 "Aceros JG se especializa en precisión y calidad en corte y transformación de acero con tecnología de punta, entregando soluciones a medida para la industria minera.",
 "parts","a","c"),
("Comercial Química Massó Chile SpA","Pabellón Plata","527","masso@cqmasso.com","","generico",
 "Química Massó en Exponor: 60 años de experiencia y leads activos",
 "Química Massó acumula más de 60 años fabricando y distribuyendo productos químicos para industria y minería, con representación de marcas propias y de terceros a nivel nacional.",
 "services","b","d"),
("Comercial Texmundo S.A.","Pabellón Oro","1119","ventas@texsco.cl","","ventas",
 "Texsco en Exponor: acero inoxidable y compradores calificados",
 "Texsco es referente en acero inoxidable para la industria, con un amplio catálogo de productos de alta calidad para las exigencias del proceso minero en el norte de Chile.",
 "parts","c","a"),
("Comercializadora Ingemerca Chile SpA","Pabellón Litio","849","info@ingemerca.cl","","ventas",
 "Ingemerca en Exponor: manejo de material y leads bien seguidos",
 "Ingemerca Chile tiene más de 30 años liderando en manejo de material y control de polvo para la minería, un servicio técnico de alta especialización con presencia en todo el norte.",
 "services","a","b"),
# ── LOTE 3 ──────────────────────────────────────────────────────────────────
("Confecciones Butka Ltda.","Pabellón Molibdeno","1250-1251","contacto@butka.com","","ventas",
 "Butka en Exponor: indumentaria ISO y compradores activos",
 "Butka ofrece indumentaria de seguridad y vestuario corporativo bajo estándares ISO, siendo proveedor de grandes mineras que exigen certificación de calidad en cada entrega.",
 "epp","b","c"),
("Confipetrol Chile SpA","Pabellón Hierro","1478","comercial@confipetrol.cl","","ventas",
 "Confipetrol en Exponor: servicios oil & gas y pipeline activo",
 "Confipetrol presta servicios especializados para oil & gas y minería, manejando proyectos de alta complejidad operacional en Chile y Latinoamérica con experiencia técnica comprobada.",
 "services","c","d"),
("Constructora Baical Ltda.-Baical Rental","Pabellón Hierro","1488","baical@baical.cl","","generico",
 "Baical en Exponor: construcción industrial y leads que no se pierden",
 "Baical se especializa en soluciones industriales, servicios técnicos, ingeniería y soporte para minería, combinando construcción con arriendo de equipos para proyectos de gran escala.",
 "constr","a","a"),
("Constructora El Sauce S.A.","Exterior C","90","ccarreno@elsauce.cl","","generico",
 "El Sauce en Exponor: movimiento de tierras y contactos activos",
 "Constructora El Sauce tiene décadas de especialización en movimiento de tierras, caminos, plataformas, pilas de lixiviación y piscinas de proceso para la minería del norte.",
 "constr","b","b"),
("Constructora El Sauce S.A.","Exterior C","90","oficina@elsauce.cl","","generico",
 "Exponor 2026: proyectos mineros y seguimiento post-feria",
 "Constructora El Sauce ejecuta obras civiles de alta complejidad para la minería, desde movimiento de tierras hasta pilas de lixiviación, con trayectoria comprobada en el norte.",
 "constr","c","c"),
("Constructora Vic","Pabellón Molibdeno","1220","contacto@constructoravic.cl","","ventas",
 "Constructora Vic en Exponor: caminos mineros y pipeline activo",
 "Constructora VIC tiene más de 30 años de experiencia en gestión de caminos mineros, fundada en Antofagasta como referente en infraestructura vial para la gran minería del norte.",
 "constr","a","d"),
("Copper Capacitación Ltda.","Pabellón Oro","1192","ventas@coppercapacitacion.cl","","ventas",
 "Exponor 2026: capacitación OTEC y alumnos bien captados",
 "Copper Capacitación es OTEC especializada en gestión de riesgos y respuesta a emergencias para minería, un servicio con alta demanda en un sector donde la seguridad es prioridad.",
 "services","b","a"),
("Corporación Proloa","Pabellón Yodo","760","secretaria@proloa.cl","","generico",
 "Proloa en Exponor: emprendimiento regional y contactos activos",
 "Corporación Proloa es entidad regional que promueve el emprendimiento en el norte de Chile, con programas activos como el Fondo Empréndate 2026 para el desarrollo local.",
 "services","c","b"),
("Cortec Corporation - Patiño Y Compañía","Pabellón Molibdeno","1315","productinfo@cortecvci.com","","generico",
 "Exponor 2026: inhibidores de corrosión Cortec y leads activos",
 "Cortec Corporation fabrica inhibidores de corrosión de clase mundial, representados en Chile por Patiño y Compañía para la industria minera e industrial del norte.",
 "services","a","c"),
("CPS Conveyors SpA","Exterior D","108","contacto@conveyorschile.cl","","ventas",
 "Conveyors Chile en Exponor: correas y oportunidades bien seguidas",
 "Conveyors Chile se orienta a la confiabilidad de correas transportadoras con atención personalizada, un servicio crítico para la continuidad operacional de las plantas mineras.",
 "services","b","d"),
("Cronostec Chile SpA","Pabellón Cobalto","1415","ventas@cronostec.cl","","ventas",
 "Exponor 2026: tecles Cronostec y compradores calificados",
 "Cronostec comercializa tecles manuales y eléctricos de cadena para izaje industrial, un equipo de alta rotación en las operaciones de mantención minera del norte.",
 "parts","c","a"),
("Crosspipe Systems S.A.","Pabellón Plata","338","izepeda@crosspipe.cl","","generico",
 "Crosspipe en Exponor: tuberías HDPE y seguimiento activo",
 "Crosspipe provee soluciones en tuberías de polietileno reticulado de diseño único, con gran resistencia química y mecánica para las aplicaciones industriales más exigentes.",
 "services","a","b"),
("CRT Chile SpA","Pabellón Litio","891","javier.fernandez@crtchile.com","Javier","personal",
 "CRT Chile en Exponor: equipos eléctricos OEM y leads activos",
 "CRT Chile ofrece servicio OEM alternativo para equipos eléctricos en minería desde 1987, con más de 30 años atendiendo los requisitos más exigentes del sector en Chile.",
 "tech","b","c"),
("Danfoss Chile","Pabellón Cobre","20","sac.chile@danfoss.com","","generico",
 "Danfoss en Exponor: automatización y seguimiento de leads",
 "Danfoss, referente global en variadores de frecuencia y automatización, tiene en Exponor una plataforma clave para conectar con proyectos de eficiencia energética en la gran minería.",
 "tech","c","d"),
("Danus Conexiones SpA","Pabellón Yodo","630","ventas@danus.cl","","ventas",
 "Danus en Exponor: conexiones eléctricas y compradores activos",
 "Danus Conexiones provee componentes y conexiones eléctricas industriales para el mercado minero, con catálogo disponible y presencia directa en Santiago para atención nacional.",
 "parts","a","a"),
("Datamine Chile S.A.","Pabellón Yodo","764","cristian.garcia@dataminesoftware.com","Cristian","personal",
 "Datamine en Exponor: software minero y demos que se cierran",
 "Datamine es líder global en software de planificación, modelamiento geológico y optimización minera, herramientas que usan las operaciones más grandes de Chile y el mundo.",
 "tech","b","b"),
("Detroit S.A.","Exterior B","053","detroit@detroit.cl","","generico",
 "Exponor 2026: motores Detroit y pipeline de ventas activo",
 "Detroit Chile representa motores industriales y marinos, generadores diesel y gas, transmisiones automáticas y repuestos para las aplicaciones más críticas de la minería.",
 "parts","c","c"),
("Diproseg Ltda.","Pabellón Plata","335","diproseg@diproseg.cl","","generico",
 "Diproseg en Exponor: extintores y compradores bien seguidos",
 "Diproseg es empresa antofagastina especializada en mantención e inspección de extintores portátiles, un servicio de cumplimiento normativo que cada faena minera necesita.",
 "epp","a","d"),
("Disegno 3D SpA","Pabellón Litio","927","ventas@disegno3d.cl","","ventas",
 "Disegno 3D en Exponor: manufactura aditiva y leads activos",
 "Disegno 3D ofrece manufactura aditiva, software CAM y soluciones de diseño para la industria, tecnologías que están cambiando cómo la minería produce piezas de repuesto a demanda.",
 "tech","b","a"),
("Disegno 3D SpA","Pabellón Litio","927","marketing@disegno3d.cl","","generico",
 "Exponor 2026: impresión 3D minera y seguimiento digital",
 "Disegno 3D está revolucionando el aprovisionamiento de piezas en minería con manufactura aditiva y software CAM, soluciones que generan alto interés entre los ingenieros de mantención.",
 "tech","c","b"),
# ── LOTE 4 ──────────────────────────────────────────────────────────────────
("Edaltec Ltda.","Pabellón Plata","345","contacto@edaltec.cl","","ventas",
 "Edaltec en Exponor: energía industrial y leads calificados",
 "Edaltec lidera soluciones de energía para la industria a nivel internacional, con proyectos de alta complejidad en electricidad y automatización para el sector minero.",
 "tech","a","c"),
("EIE Ingeniería SpA","Pabellón Litio","851","info@eiengineering.net","","ventas",
 "EiE Ingeniería en Exponor: correas y oportunidades activas",
 "EiE Ingeniería presta servicios técnicos en mecánica y electromecánica, especializándose en equipos para transporte de materiales sólidos a granel y cintas transportadoras.",
 "services","b","d"),
("ELB - Transportes El Libertador","Exterior A","025","copiapo@elb.cl","","generico",
 "Exponor 2026: logística de sobredimensión y leads bien seguidos",
 "El Libertador es partner logístico especialista en transporte de carga segura y de sobredimensión, con presencia en Copiapó, Antofagasta y Santiago para proyectos mineros.",
 "services","c","a"),
("ELB - Transportes El Libertador","Exterior A","025","santiago@elb.cl","","generico",
 "ELB en Exponor: transporte pesado y pipeline de contactos",
 "El Libertador opera transporte de carga general y sobredimensión en el norte de Chile con los más altos estándares de seguridad, siendo socio logístico de confianza para la minería.",
 "services","a","b"),
("ELB - Transportes El Libertador","Exterior A","025","antofagasta@elb.cl","","generico",
 "Exponor 2026: carga minera y seguimiento post-stand",
 "El Libertador tiene base operacional en Antofagasta para atender el transporte de carga de los proyectos mineros más exigentes del norte, con flota y experiencia para cargas complejas.",
 "services","b","c"),
("Electroweather S.A.","Pabellón Litio","836","contacto@electroweather.cl","","ventas",
 "Electroweather en Exponor: sistemas eléctricos y leads activos",
 "Electroweather es experto en sistemas eléctricos industriales con planificación técnica para operaciones exigentes, desde ingeniería hasta implementación y mantenimiento continuo.",
 "tech","c","d"),
("Emeser Ltda.","Exterior A","029","lisandrovasquez@emeser.cl","","generico",
 "Emeser en Exponor: cabinas CAEX y compradores bien seguidos",
 "Emeser lleva más de 10 años especializándose en reparación de asientos Grammer e ISRI, frenos hidráulicos CAEX y mantención de cabinas para equipos mineros en Antofagasta.",
 "parts","a","a"),
("Endress + Hauser Chile Ltda.","Pabellón Yodo","690","info.cl@endress.com","","ventas",
 "Endress+Hauser en Exponor: instrumentación y demos que cierran",
 "Endress+Hauser, referente global en instrumentación de proceso, tiene presencia directa en Chile con equipos de medición de flujo, nivel y presión para la gran minería.",
 "tech","b","b"),
("Enrique Osses E. y Cía. Ltda.","Pabellón Litio","972","contacto@osses.cl","","ventas",
 "Exponor 2026: ¿Osses y Cía. tiene su pipeline listo?",
 "Enrique Osses y Cía. atiende a la industria del norte de Chile con productos y servicios técnicos especializados para el mercado minero, con trayectoria reconocida en la región.",
 "services","c","c"),
("Environmental Monitoring Services SpA (EMS Chile)","Pabellón Litio","909","contacto@ems-chile.com","","ventas",
 "EMS Chile en Exponor: monitoreo ambiental y contactos activos",
 "EMS Chile provee monitoreo ambiental para proyectos industriales, gestionando calidad del aire, agua y suelo, un requisito ineludible para las operaciones mineras actuales.",
 "services","a","d"),
("Eurocomercial Sistemas Contra Incendios","Pabellón Yodo","800","info@eurocomercial.cl","","ventas",
 "Eurocomercial en Exponor: contra incendios y leads calificados",
 "Eurocomercial diseña, instala y mantiene sistemas contra incendios para la industria, con venta de extintores, gabinetes y mangueras para entornos mineros exigentes del norte.",
 "epp","b","a"),
("Eurohinca Chile","Pabellón Hierro","1490","info@eurohinca.com","","ventas",
 "Eurohinca en Exponor: microtúneles y proyectos bien seguidos",
 "Eurohinca se especializa en ejecución de microtúneles sin zanja con tuneladoras teledirigidas, tecnología de precisión para proyectos de infraestructura subterránea minera.",
 "constr","c","b"),
("Eurostandard Chile S.A.","Pabellón Litio","966","ventas@eurostandard.cl","","ventas",
 "Eurostandard en Exponor: calidad, seguridad y pipeline activo",
 "Eurostandard se posiciona en la especialización y compromiso con la calidad, seguridad e innovación industrial, con soluciones para los estándares más exigentes del sector minero.",
 "services","a","c"),
("Evolog SpA","Pabellón Cobre","121","contacto@evolog.cl","","ventas",
 "Evolog en Exponor: logística inteligente y leads activos",
 "Evolog ofrece barreras Boplan, racks y demarcación para proyectos logísticos industriales, productos de alta demanda en los centros de acopio y bodegas de las operaciones mineras.",
 "parts","b","d"),
("Fábrica Moisés Calama","Pabellón Molibdeno","1272","contacto@fabricamoises.cl","","ventas",
 "Fábrica Moisés en Exponor: EPP local y compradores activos",
 "Fábrica Moisés es manufactura local en Calama especializada en ropa de trabajo corporativa, EPP y vestuario de seguridad, con conocimiento directo del entorno minero del norte.",
 "epp","c","a"),
("Faros Chile","Pabellón Hierro","1503","contacto@faros.cl","","ventas",
 "Faros Chile en Exponor: TI minera y pipeline de oportunidades",
 "Faros Chile se enfoca en consultoría TI y logística para la minería y retail, combinando tecnología e inteligencia operacional para mejorar la eficiencia de las operaciones.",
 "tech","a","b"),
("FASTECH SOLUCIONES TECNOLOGICAS LTDA.","Pabellón Cobre","247","web@fastech.cl","","generico",
 "Fastech en Exponor: proyectos tech y leads bien gestionados",
 "Fastech nació en 2009 en servicios, desarrollo e implementación de proyectos de ingeniería tecnológica para la industria, con más de 15 años de trayectoria en proyectos mineros.",
 "tech","b","c"),
("Fernorte Comercializadora Industrial","Pabellón Cobre","200","fernortechile@gmail.com","","generico",
 "Exponor 2026: torque controlado y compradores calificados",
 "Fernorte es especialista en torque controlado, importador y proveedor para empresas contratistas y mineras de la región norte, con servicio técnico local en Antofagasta.",
 "parts","c","d"),
("FG Logistica SpA","Pabellón Cobalto","1393","contacto@fglogistica.cl","","ventas",
 "FG Logística en Exponor: carga y seguimiento post-stand",
 "FG Logística provee servicios de carga, importación y exportación, siendo un actor clave en la cadena de suministro de los proveedores y operadores mineros del norte.",
 "services","a","a"),
# ── LOTE 5 ──────────────────────────────────────────────────────────────────
("Flow Systems SpA","Pabellón Plata","486","contacto@flow-systems.cl","","ventas",
 "Flow Systems en Exponor: fluidos y oportunidades activas",
 "Flow Systems provee sistemas de riego y fluidos para minería y agricultura, integrando tecnología de control para las operaciones más exigentes del norte de Chile.",
 "tech","b","b"),
("Flowserve Chile SpA","Pabellón Cobre","277","susekar@flowserve.com","","generico",
 "Flowserve en Exponor: bombas críticas y pipeline de ventas",
 "Flowserve, referente global en bombas, válvulas y sellos de proceso, tiene presencia directa en Chile para atender las necesidades más críticas de la gran minería.",
 "tech","c","c"),
("Fluycom SpA","Pabellón Molibdeno","1264","ventas@fluycom.cl","","ventas",
 "Fluycom en Exponor: aceros especiales y leads calificados",
 "Fluycom es líder nacional en suministro de aceros especiales para minería, con un catálogo técnico que los jefes de mantenimiento buscan activamente en cada feria del sector.",
 "parts","a","d"),
("Foxmin Ltda.","Pabellón Plata","521","contacto@foxmin.cl","","ventas",
 "Foxmin en Exponor: calzado Lithium y compradores activos",
 "Foxmin provee calzado y EPP de alto rendimiento para jornadas exigentes en minería, incluyendo la nueva línea Lithium LT 502 diseñada para confort y seguridad en faena.",
 "epp","b","a"),
("Green Leader SpA","Pabellón Cobalto","1369","contacto@greenleader.cl","","ventas",
 "Green Leader en Exponor: ESG, economía circular y leads",
 "Green Leader diseña y ejecuta soluciones innovadoras de Economía Circular con criterios ESG, ayudando a operaciones mineras a cumplir sus metas de sostenibilidad y reporte.",
 "tech","c","b"),
("Grupo Antko","Pabellón Molibdeno","1248","ventas@antko.cl","","ventas",
 "Antko en Exponor: soluciones en agua y pipeline activo",
 "Antko ofrece soluciones integrales en agua para la industria: acero, válvulas, HDPE, termoplásticos y filtración, portafolio técnico que atiende múltiples necesidades del proceso minero.",
 "parts","a","c"),
("Grupo Belator","Pabellón Plata","613","contacto@belator.cl","","ventas",
 "Belator en Exponor: seguridad integrada y oportunidades activas",
 "Grupo Belator entrega proyectos de seguridad integrados para infraestructura crítica, garantizando continuidad operacional en sectores mineros e industriales del norte.",
 "services","b","d"),
("Grupo Belator","Pabellón Plata","613","contacto@grupobelator.cl","","ventas",
 "Grupo Belator en Exponor: ¿tienen su pipeline de leads listo?",
 "Grupo Belator asegura la continuidad operacional de infraestructura crítica con proyectos de seguridad integrados, un servicio de alto valor para los operadores mineros que estarán en Exponor.",
 "services","c","a"),
("Grupo Genera Ltda.","Pabellón Litio","1016","ventas@grupogenera.cl","","ventas",
 "Grupo Genera en Exponor: generadores y energía bien gestionada",
 "Grupo Genera es experto en arriendo y servicios de grupos electrógenos, energía de respaldo crítica para faenas mineras remotas que no pueden permitirse cortes de suministro.",
 "services","a","b"),
("Grupo Inka Coya","Exterior E","133","cotizaciones@inkacoya.cl","","generico",
 "Inka Coya en Exponor: servicios Calama y leads activos",
 "Grupo Inka Coya entrega servicios integrales en Calama para minería: hotelería empresarial, alimentación en faenas y transporte especializado en la región de Atacama.",
 "services","b","c"),
("Grupo Ipsa","Pabellón Cobalto","1404","administracion@grupoipsa.cl","","generico",
 "Exponor 2026: datacenter modular y contactos bien seguidos",
 "Grupo Ipsa es pionero en instalación de Datacenter Modular en Chile desde 2013, con sistema de monitoreo 24/7 para la infraestructura digital crítica de las operaciones mineras.",
 "tech","c","d"),
("Grupo Lampa","Pabellón Litio","958","info@grupolampa.com","","ventas",
 "Grupo Lampa en Exponor: valorización sostenible y leads activos",
 "Grupo Lampa ofrece procesamiento, valorización, logística y trazabilidad con enfoque en sostenibilidad, propuesta de valor que conecta con los objetivos ESG de la gran minería.",
 "services","a","a"),
("Grupo Maritex","Pabellón Plata","377-428","ecommerce@grupomaritex.cl","","generico",
 "Exponor 2026: textiles industriales y compradores calificados",
 "Grupo Maritex suministra ropa de trabajo, vestuario corporativo y línea Heavy Duty para la industria, con amplio catálogo para los equipos de faena minera del norte.",
 "epp","b","b"),
("GSP-Chile","Pabellón Plata","533-534","info@gsp-chile.com","","ventas",
 "GSP Chile en Exponor: EPP certificado y pipeline activo",
 "GSP Chile provee productos de alta calidad certificados en EPP y seguridad industrial, con respaldo técnico para las exigencias de seguridad de la gran minería.",
 "epp","c","c"),
("GSP-Chile","Pabellón Plata","533-534","soporteventas@gsp-chile.com","","generico",
 "Exponor 2026: soporte EPP y seguimiento post-stand",
 "GSP Chile tiene un equipo de soporte técnico para EPP y seguridad industrial, asegurando que cada cliente tenga la respuesta correcta cuando la necesita en su operación.",
 "epp","a","d"),
("H Briones S.A.","Pabellón Litio","899","hbse@hbriones.com","","generico",
 "H Briones en Exponor: sistemas eléctricos y leads activos",
 "H. Briones Sistemas Eléctricos ofrece proyectos y soluciones de calidad en suministro de energía eléctrica a lo largo de Chile, con especialización en proyectos industriales complejos.",
 "tech","b","a"),
("HCA Minería","Exterior C","093-099","ventas@hcamineria.cl","","ventas",
 "HCA Minería en Exponor: seguridad, eficiencia y leads activos",
 "HCA Minería ofrece servicios y productos de clase mundial para una minería más segura, eficiente y sostenible: drenaje, ventilación, puertas mineras, monitoreo y chancado.",
 "services","c","b"),
("Hidronor Chile","Pabellón Litio","962","contacto@hidronor.cl","","ventas",
 "Hidronor en Exponor: residuos industriales y pipeline activo",
 "Hidronor Chile es especialista en gestión y tratamiento de residuos industriales, remediación de suelos contaminados y revalorización de residuos para la minería.",
 "services","a","c"),
("Hidronor Chile","Pabellón Litio","962","ventas@hidronor.cl","","ventas",
 "Exponor 2026: tratamiento de residuos y seguimiento de leads",
 "Hidronor gestiona la cadena completa de residuos industriales para la minería, desde la recolección hasta la revalorización, con presencia activa en las operaciones del norte.",
 "services","b","d"),
("Hidropower Ltda.","Pabellón Litio","861","ventas@hidropower.cl","","ventas",
 "Exponor 2026: hidráulica y oportunidades bien capturadas",
 "Hidropower provee soluciones hidráulicas y de potencia para la industria, con servicio técnico especializado para los sistemas más críticos de la operación minera.",
 "parts","c","a"),
# ── LOTE 6 ──────────────────────────────────────────────────────────────────
("Hidropower Ltda.","Pabellón Litio","861","daniel.espinozaa@hidropower.cl","Daniel","personal",
 "Exponor 2026, Daniel: ¿tienen el sistema de leads listo?",
 "Hidropower ofrece soluciones hidráulicas y de potencia con servicio técnico especializado, y en Exponor van a conectar con compradores que buscan confiabilidad en sus sistemas críticos.",
 "parts","a","b"),
("Hidropower Ltda.","Pabellón Litio","861","administracion@hidropower.cl","","generico",
 "Exponor 2026: hidráulica industrial y pipeline de ventas",
 "Hidropower atiende a la minería con sistemas hidráulicos de alta confiabilidad y soporte técnico directo, un servicio que genera conversaciones de alto valor en Exponor.",
 "parts","b","c"),
("Hima Ltda.","Pabellón Molibdeno","1313-1314","ventas01@hima.cl","","ventas",
 "Hima en Exponor: EPP ignífugo y compradores calificados",
 "Hima provee ropa EPP ignífuga FR y AR certificada por ISP, overoles ignífugos y protección contra arco eléctrico para minería e industria, un producto de alta exigencia normativa.",
 "epp","b","d"),
("Hima Ltda.","Pabellón Molibdeno","1313-1314","contacto@hima.cl","","ventas",
 "Exponor 2026: ropa ignífuga Hima y leads bien seguidos",
 "Hima ofrece indumentaria de protección contra arco eléctrico certificada para la minería chilena, con presencia directa en Antofagasta para atender las operaciones del norte.",
 "epp","c","a"),
("Hofmann Engineering Chile Ltda.","Exterior C","077","chile@hofmannengineering.com","","generico",
 "Hofmann Engineering en Exponor: encoders y pipeline activo",
 "Hofmann Engineering, filial alemana, provee sistemas de encoders robustos y tecnología de accionamiento para industria pesada, soluciones de alta confiabilidad en condiciones extremas.",
 "tech","a","b"),
("Hofmann Engineering Chile Ltda.","Exterior C","077","larry.barry@hofmannengineering.com","Larry","personal",
 "Larry, Exponor 2026: encoders Hofmann y leads bien gestionados",
 "Hofmann Engineering lleva décadas construyendo tecnología de accionamiento robusta para los entornos industriales más exigentes, y Exponor es donde los ingenieros de mantención los buscan.",
 "tech","b","c"),
("Hofmann Engineering Chile Ltda.","Exterior C","077","barrie.smith@hofmannengineering.com","Barrie","personal",
 "Barrie, Exponor 2026: ¿tienen sistema de seguimiento de leads?",
 "Hofmann Engineering ofrece encoders y tecnología de accionamiento para industria pesada que superan los desafíos más duros, soluciones que generan alto interés entre los ingenieros mineros.",
 "tech","c","d"),
("Hormigones Copat Ltda.","Pabellón Yodo","682","contacto@copat.cl","","ventas",
 "Copat en Exponor: hormigón certificado y leads calificados",
 "Hormigones Copat ofrece mezclas certificadas y entrega puntual de concreto en Antofagasta, solucionando las necesidades de construcción industrial con estándares de calidad minera.",
 "constr","a","a"),
("Hosch Chile","Pabellón Cobre","31-64","sergio.lizana@hosch.cl","Sergio","personal",
 "Sergio, Exponor 2026: raspadores Hosch y leads que cierran",
 "Hosch Chile provee raspadores de correas transportadoras de alta tecnología, componente crítico para la confiabilidad y eficiencia de las plantas de procesamiento minero.",
 "parts","b","b"),
("Hri S.A.","Pabellón Cobalto","1349","info@hri.cl","","ventas",
 "HRI en Exponor: 50 años en transporte de materiales",
 "HRI S.A. tiene más de 50 años proveyendo soluciones, equipos y servicios para el transporte de materiales en la industria chilena, con experiencia en los proyectos más grandes del norte.",
 "services","c","c"),
("Hs Rodados Mantenimiento y Servicios Spa","Pabellón Oro","1111","cmunoz@hsrodados.cl","","generico",
 "HS Rodados en Exponor: mantención de rodados y pipeline activo",
 "HS Rodados está especializado en mantenimiento y reparación de trenes de rodados para equipos mineros multimarca, con servicio técnico directo en Antofagasta.",
 "parts","a","d"),
("Huebner Chile","Pabellón Cobre","43","miguel.castillo@huebner-chile.cl","Miguel","personal",
 "Miguel, Exponor 2026: encoders Huebner y leads bien seguidos",
 "Huebner Chile representa la marca alemana en encoders robustos y tecnología de accionamiento para industria pesada, soluciones de alta confiabilidad en condiciones extremas.",
 "tech","b","a"),
("Huebner Chile","Pabellón Cobre","43","ralf.albujar@huebner-peru.pe","Ralf","personal",
 "Ralf, Exponor 2026: ¿Huebner tiene su pipeline listo?",
 "Huebner ofrece sistemas de encoders y tecnología de accionamiento para los entornos industriales más duros, y Exponor 2026 es la feria donde los operadores mineros los van a buscar.",
 "tech","c","b"),
("IGD Chile","Pabellón Oro","1132","contacto@igdchile.com","","ventas",
 "IGD Chile en Exponor: ingeniería minera y oportunidades activas",
 "IGD Chile se especializa en diseño de ingeniería para minería e industria, incluyendo encapsulamiento de estructuras y proyectos de alta complejidad técnica para el norte.",
 "services","a","c"),
("Imer Chile (Cappellotto - Fassi)","Exterior B","043","info@imerchile.cl","","ventas",
 "Imer Chile en Exponor: grúas Fassi y pipeline de ventas activo",
 "Imer Chile es líder en venta y mantención de grúas articuladas Fassi, Cappellotto, Marrel y otras marcas, con servicio para los equipos de manejo de carga en la minería.",
 "services","b","d"),
("Inbox Technology Chile","Pabellón Cobalto","1374","inboxsa@inboxsa.com","","generico",
 "Inbox Technology en Exponor: analítica y leads calificados",
 "Inbox Technology lidera en instrumentación analítica para laboratorios e industrias, con equipos avanzados y soporte técnico para los laboratorios de análisis de la gran minería.",
 "tech","c","a"),
("Indutecnica Chacon SIC SpA","Pabellón Cobre","151","ventas@indutecnica.cl","","ventas",
 "Indutecnica en Exponor: soluciones técnicas y pipeline activo",
 "Indutecnica Chacon provee soluciones técnicas industriales para la minería y manufactura, con especialización en suministros de calidad para las operaciones del norte.",
 "parts","a","b"),
("Ingemecanic Ingeniería SpA","Pabellón Plata","485","williams.rebolledo@ingemecanic.cl","Williams","personal",
 "Williams, Exponor 2026: ingeniería integral y leads activos",
 "Ingemecanic ofrece desarrollo integral de proyectos en mecánica, piping, estructuras, obras civiles y electro-control, innovando en soluciones integrales para la industria minera.",
 "services","b","c"),
("Ingeniería y Servicios Orbitec SpA","Pabellón Molibdeno","1234","contacto@orbitec.cl","","ventas",
 "Orbitec en Exponor: equipos ambientales y oportunidades activas",
 "Orbitec provee vehículos especializados y equipos de aplicaciones ambientales fabricados a pedido, con soluciones para los requerimientos más específicos de la minería.",
 "services","c","d"),
("Ingeteco SpA","Pabellón Molibdeno","1260","cotizaciones@ingeteco.cl","","generico",
 "Ingeteco en Exponor: contra incendios y leads calificados",
 "Ingeteco lidera en ingeniería, montaje y servicios de detección y extinción de incendios, con contratos activos en las principales operaciones mineras del norte.",
 "epp","a","a"),
# ── LOTE 7 ──────────────────────────────────────────────────────────────────
("Inppa Servicios Industriales SpA","Exterior E","137","valentina.carracedo@inpparadiadores.cl","Valentina","personal",
 "Valentina, Exponor 2026: radiadores y leads que cierran",
 "Inppa Radiadores se especializa en radiadores e intercambiadores de calor para equipos mineros, con presencia en Antofagasta y Santiago para atender las operaciones del norte.",
 "parts","b","b"),
("Inppa Servicios Industriales SpA","Exterior E","137","odette.coydan@inpparadiadores.cl","Odette","personal",
 "Odette, Exponor 2026: Inppa y seguimiento de compradores",
 "Inppa ofrece radiadores e intercambiadores de calor con servicio técnico especializado, productos de alta demanda en las flotas de camiones mineros del norte.",
 "parts","c","c"),
("Inppa Servicios Industriales SpA","Exterior E","137","luisiana.chico@inpparadiadores.cl","Luisiana","personal",
 "Luisiana, Exponor 2026: ¿Inppa tiene el sistema de leads listo?",
 "Inppa Radiadores atiende a la gran minería del norte con radiadores e intercambiadores de calor de primera calidad, con cobertura en Antofagasta y Santiago.",
 "parts","a","d"),
("Inquinat Chile Ltda","Pabellón Oro","1046","ventas.cl@inquinat.com","","ventas",
 "Inquinat en Exponor: tratamiento de aguas y pipeline activo",
 "Inquinat Chile es líder en tratamiento de aguas industriales con tecnología propia y proyectos de gran envergadura, un servicio crítico para las plantas mineras del norte.",
 "services","b","a"),
("Instruvalve SpA","Pabellón Cobre","150","ventas@instruvalve.cl","","ventas",
 "Instruvalve en Exponor: automatización y leads calificados",
 "Instruvalve provee automatización, control de procesos y manejo de fluidos para industria y minería, con catálogo técnico amplio y soporte local en Chile.",
 "tech","c","b"),
("Intronica Ltda. - Fluke","Pabellón Plata","282","ventas@intronica.com","","ventas",
 "Intronica Fluke en Exponor: instrumentos y compradores activos",
 "Intronica es Distribuidor Master de Fluke y Tektronix en Chile, con el catálogo más completo de instrumentos de medición para variables eléctricas y electrónicas industriales.",
 "parts","a","c"),
("Intronica Ltda. - Fluke","Pabellón Plata","282","bodega@intronica.com","","generico",
 "Exponor 2026: Fluke para minería y seguimiento post-stand",
 "Intronica distribuye la línea completa de Fluke y Tektronix en Chile, instrumentos de referencia para los técnicos e ingenieros de la gran minería que estarán en Exponor.",
 "parts","b","d"),
("Isva SpA","Pabellón Litio","931","ventas@isva.cl","","ventas",
 "Isva en Exponor: iluminación industrial y leads activos",
 "Isva SpA ofrece ingeniería y servicios con foco en iluminación y automatización para la industria, con soluciones técnicas para operaciones que exigen confiabilidad continua.",
 "tech","c","a"),
("Isva SpA","Pabellón Litio","931","venta.empresas@isva.cl","Venta","personal",
 "Exponor 2026: automatización Isva y pipeline de empresas",
 "Isva ofrece soluciones de automatización e iluminación industrial para la minería, y Exponor es la plataforma ideal para conectar con los proyectos más grandes del sector.",
 "tech","a","b"),
("Isva SpA","Pabellón Litio","931","secretaria@isva.cl","","generico",
 "Exponor 2026: Isva y seguimiento de oportunidades de negocio",
 "Isva SpA provee ingeniería y servicios de automatización e iluminación industrial, atendiendo a operaciones mineras que necesitan confiabilidad en sus sistemas críticos.",
 "tech","b","c"),
("ITL Chile","Pabellón Oro","1079A","contacto@itlchile.com","","ventas",
 "ITL Chile en Exponor: tecnologías limpias y leads activos",
 "El ITL es el Centro de Innovación en Tecnologías Limpias, impulsando soluciones sustentables para minería, energía y litio con enfoque en el futuro del sector productivo.",
 "tech","c","d"),
("Itsanet S.A.","Pabellón Molibdeno","1230-1231","contactos@itsanet.com","","ventas",
 "Itsanet en Exponor: logística regional y pipeline activo",
 "Itsanet es el socio logístico de confianza en la región, con servicios de almacenaje, distribución y logística de última milla para proveedores mineros del norte.",
 "services","a","a"),
("Klinger Chile","Pabellón Plata","523","gral@klinger.cl","","generico",
 "Klinger Chile en Exponor: sellos industriales y leads activos",
 "Klinger Chile, filial del Grupo Klinger de Austria, es referencia en control de fluidos y tecnología de sellado, con décadas de presencia reconocida en la minería chilena.",
 "parts","b","b"),
("Klinger Chile","Pabellón Plata","523","gral@saidi.es","","generico",
 "Exponor 2026: Klinger/Saidi y seguimiento de oportunidades",
 "Klinger Chile opera como parte del grupo Klinger y Saidi, especialistas globales en sellado y control de fluidos para las condiciones más exigentes de la industria minera.",
 "parts","c","c"),
("Krah America Latina S.A.","Pabellón Plata","432-434","immo@reichenbaecher.eu","","generico",
 "Krah en Exponor: tuberías HDPE y pipeline de proyectos",
 "Krah America Latina fabrica tuberías HDPE de diseño único para proyectos de agua, drenaje e infraestructura industrial, con tecnología filial de Krah Austria para aplicaciones exigentes.",
 "services","a","d"),
("Loa Rental SpA","Exterior A","031","contacto@loarental.cl","","ventas",
 "Loa Rental en Exponor: arriendo norte y leads calificados",
 "Loa Rental ofrece construcción, mantención y arriendo de equipos multidisciplinarios para el norte minero, con base en Antofagasta y experiencia en proyectos de gran escala.",
 "services","b","a"),
("Lockerplus SpA","Pabellón Cobre","198-199","contacto@lockerplus.cl","","ventas",
 "Exponor 2026: casilleros inteligentes y pipeline activo",
 "Lockerplus provee casilleros inteligentes para instalaciones industriales, solución que las empresas mineras buscan para gestionar activos personales de sus operadores en faena.",
 "tech","c","b"),
("Lorbrand S.A.","Exterior D","106","chile@lorbrand.com","","generico",
 "Lorbrand en Exponor: correas especializadas y leads activos",
 "Lorbrand es proveedor mundial de sistemas de correa transportadora de alta especialización, reconocido globalmente por las grandes mineras como socio técnico de confianza.",
 "services","a","c"),
# ── LOTE 8 ──────────────────────────────────────────────────────────────────
("Madepal SpA","Pabellón Oro","1081","ventas@madepal.cl","","ventas",
 "Madepal en Exponor: pallets a medida y clientes activos",
 "Madepal es líder en fabricación y distribución de pallets, embalajes de exportación y collares para cajones plegables, con soluciones logísticas para toda la industria.",
 "parts","b","d"),
("Maisver Mecanizados Ltda.","Pabellón Molibdeno","1308","maisver@maisver.cl","","generico",
 "Maisver en Exponor: electromecánica industrial y leads activos",
 "Maisver se especializa en electromecánica industrial: motores eléctricos, bombas, balanceo dinámico, alineación láser y mantención electromecánica para equipos críticos de minería.",
 "parts","c","a"),
("Maisver Mecanizados Ltda.","Pabellón Molibdeno","1308","contabilidad@maisver.cl","","generico",
 "Exponor 2026: Maisver y seguimiento post-feria",
 "Maisver tiene la capacidad de atender la electromecánica industrial completa, desde motores eléctricos hasta bombas y balanceo dinámico, para las operaciones mineras del norte.",
 "parts","a","b"),
("Maisver Mecanizados Ltda.","Pabellón Molibdeno","1308","contabilidad2@maisver.cl","","generico",
 "Maisver en Exponor 2026: ¿cómo siguen a sus contactos?",
 "Maisver ofrece el espectro completo de la electromecánica industrial para minería, con alineación láser, embobinado industrial y mantención de equipos críticos.",
 "parts","b","c"),
("Mammoet Chile","Pabellón Cobre","128","vanessa.labana@mammoet.com","Vanessa","personal",
 "Vanessa, Exponor 2026: izaje pesado y leads bien gestionados",
 "Mammoet Chile lleva más de una década resolviendo problemas complejos de izaje y transporte pesado en Chile, con el respaldo de más de 200 años de experiencia global.",
 "services","c","d"),
("Marlew S.A.","Pabellón Litio","937","info@marlew.com.ar","","ventas",
 "Marlew en Exponor: conductores eléctricos y pipeline activo",
 "Marlew tiene más de 50 años fabricando conductores eléctricos de calidad con innovación constante, atendiendo proyectos industriales y mineros en toda Sudamérica.",
 "parts","a","a"),
("Marlew S.A.","Pabellón Litio","937","sales@marlew.com.ar","","ventas",
 "Exponor 2026: conductores Marlew y leads que no se pierden",
 "Marlew fabrica conductores eléctricos de alta calidad desde hace más de 50 años, siendo proveedor de referencia para proyectos de electrificación minera en el norte de Chile.",
 "parts","b","b"),
("Marlew S.A.","Pabellón Litio","937","ventas@marlew.com.ar","","ventas",
 "Marlew en Exponor 2026: cables y oportunidades activas",
 "Marlew ofrece el portafolio más completo en conductores eléctricos para aplicaciones industriales y mineras, con innovación y calidad respaldada por más de medio siglo.",
 "parts","c","c"),
("MATMIN SPA","Pabellon Yodo","634","matmin@matmin.cl","","generico",
 "Matmin en Exponor: pesajes dinámicos y leads calificados",
 "Matmin lidera en pesajes dinámicos para la industria minera, con soluciones de control de carga para los procesos de extracción y transporte del norte de Chile.",
 "tech","a","d"),
("Metalmack Limitada","Pabellón Cobalto","1381","dmackenzie@metalmack.cl","","generico",
 "Metalmack en Exponor: soluciones robustas y pipeline activo",
 "Metalmack ofrece soluciones robustas y de calidad en mecanizado y metalurgia, con un catálogo de productos para los requerimientos más exigentes de la industria.",
 "parts","b","a"),
("Metaservice Ltda.","Pabellón Plata","556","contacto@metaservice.cl","","ventas",
 "Metaservice en Exponor: datacenter y telecomunicaciones mineras",
 "Metaservice provee soluciones avanzadas para data centers, seguridad de redes y telecomunicaciones, servicios que la minería digitalizada requiere para operar con confiabilidad.",
 "tech","c","b"),
("Métrica SpA","Pabellón Litio","984-991","contacto@metrica.cl","","ventas",
 "Métrica en Exponor: energía crítica y leads bien seguidos",
 "Métrica es el aliado estratégico en respaldo y almacenamiento de energía crítica para operaciones que no pueden permitirse interrupciones de suministro eléctrico.",
 "tech","a","c"),
("Micr'Eau Chile","Pabellón Cobre","170","p.guasp@micreau.fr","","generico",
 "Micr'Eau en Exponor: tratamiento de agua y pipeline activo",
 "Micr'Eau es empresa de ingeniería de tratamiento de agua potable con presencia en Europa y Chile, aplicando tecnologías de filtración avanzada para proyectos industriales y mineros.",
 "services","b","d"),
("Mine Partner Soluciones Generales Para La Minería, S.A.","Pabellón Yodo","737","ventas@minepartner.cl","","ventas",
 "Mine Partner en Exponor: reparación minera y leads activos",
 "Mine Partner ofrece reparación de herramientas, fabricación de equipos mineros y arriendo de camión tolva en Antofagasta, cubriendo las necesidades operacionales más urgentes.",
 "parts","c","a"),
("Mine Trust SpA","Exterior A","035","contacto@minetrust.com","","ventas",
 "Mine Trust en Exponor: confiabilidad minera y oportunidades",
 "Mine Trust se posiciona como el partner de confiabilidad que mantiene en marcha a la gran minería, con servicios técnicos para operaciones que no toleran tiempos de detención.",
 "services","a","b"),
("MJI Ltda.","Pabellón Oro","1125","ventas@mjiltda.cl","","ventas",
 "MJI en Exponor: químicos sostenibles y pipeline activo",
 "MJI desarrolla productos químicos orgánicos y sostenibles para agricultura y minería, contribuyendo a mejorar la producción mientras reduce el impacto ambiental de las operaciones.",
 "services","b","c"),
("MJI Ltda.","Pabellón Oro","1125","epalacios@mjiltda.cl","","generico",
 "Exponor 2026: MJI químicos orgánicos y seguimiento de leads",
 "MJI ofrece el portafolio más completo en productos químicos sostenibles para la minería, con soluciones que los equipos de proceso buscan en cada feria del sector.",
 "services","c","d"),
("Módulos S.A.","Exterior B","069","info@modulos.cl","","ventas",
 "Módulos S.A. en Exponor: baños móviles y leads calificados",
 "Módulos S.A. provee baños móviles y soluciones portables para llevar el trabajo donde se necesite, infraestructura temporal indispensable en faenas mineras remotas.",
 "services","a","a"),
# ── LOTE 9 ──────────────────────────────────────────────────────────────────
("MT Equipos SpA","Pabellón Yodo","793","ventas@mtmingenieria.cl","","ventas",
 "MT Equipos en Exponor: máquinas mineras y pipeline activo",
 "MT Equipos fabrica máquinas y equipos para minería, construyendo soluciones técnicas a medida para los procesos más específicos de la gran minería del norte.",
 "parts","b","b"),
("MT Equipos SpA","Pabellón Yodo","793","martin.tapia@mtmingenieria.cl","Martin","personal",
 "Martin, Exponor 2026: MT Equipos y leads que no se pierden",
 "MT Equipos diseña y construye maquinaria para minería adaptada a cada proceso, un producto técnico de alto valor donde el seguimiento personalizado hace la diferencia.",
 "parts","c","c"),
("Mtm Solutions SpA","Pabellón Cobalto","1427","ventas@mtmingenieria.cl","","ventas",
 "Mtm Solutions en Exponor: soluciones industriales y leads activos",
 "Mtm Solutions provee soluciones industriales para minería, con maquinaria y equipos de alta ingeniería para los procesos más exigentes del norte de Chile.",
 "parts","a","d"),
("Mtm Solutions SpA","Pabellón Cobalto","1427","martin.tapia@mtmingenieria.cl","Martin","personal",
 "Martin, Exponor 2026: Mtm Solutions y pipeline de ventas",
 "Mtm Solutions construye maquinaria y soluciones para minería con foco técnico, y Exponor es la plataforma donde los jefes de proyecto buscan proveedores de este calibre.",
 "parts","b","a"),
("Nilos Chile","Pabellón Cobre","89","info@nilos.de","","ventas",
 "Nilos en Exponor: conexión de correas y leads calificados",
 "Nilos, empresa alemana, provee adhesivos y soluciones de conexión de correas transportadoras de máxima durabilidad, 100% hechas en Alemania para las condiciones más exigentes.",
 "parts","c","b"),
("Nowpartschile","Pabellón Hierro","1464","ventas@nowparts.cl","","ventas",
 "Nowparts en Exponor: repuestos industriales y pipeline activo",
 "Nowparts Chile es importadora especializada en repuestos, suministros y componentes para la industria en Antofagasta, con alquiler de maquinaria y tecnología de punta.",
 "parts","a","c"),
("Pavimentos Quilín Ltda.","Pabellón Plata","529","ventas@quilin.cl","","ventas",
 "Quilín en Exponor: pavimentos y proyectos bien seguidos",
 "Quilín tiene más de 40 años en soluciones de ingeniería y construcción vial, pavimentos y movimiento de tierra, siendo una de las trayectorias más largas en infraestructura minera.",
 "constr","b","d"),
("Pessa S.A.","Pabellón Cobre","183-219","pessa@pessa.cl","","generico",
 "Pessa en Exponor: ingeniería minera y leads calificados",
 "Pessa es empresa de ingeniería con más de una década entregando soluciones innovadoras a la minería para aumentar productividad, optimizar energía y reducir costos operacionales.",
 "tech","c","a"),
("Planve SpA","Pabellón Oro","1107","contacto@planve.cl","","ventas",
 "Planve en Exponor: gestión de residuos y pipeline activo",
 "Planve se dedica a la gestión de residuos, operación y mantenimiento de plantas de tratamiento, un servicio ambiental crítico para las operaciones mineras del norte.",
 "services","a","b"),
("Plastigen SpA","Pabellón Oro","1199","contacto@plastigen.cl","","ventas",
 "Plastigen en Exponor: polímeros industriales y leads activos",
 "Plastigen provee soluciones en polímeros y productos industriales con la mejor calidad del mercado, atendiendo a toda la cadena de suministro de la minería.",
 "parts","b","c"),
("Plastigen SpA","Pabellón Oro","1199","rrojas@plastigen.cl","","generico",
 "Exponor 2026: polímeros Plastigen y seguimiento post-stand",
 "Plastigen tiene el catálogo más completo en polímeros y productos industriales para minería, con soluciones que los equipos de compras buscan en cada feria del sector.",
 "parts","c","d"),
("PQC Consultores SpA","Pabellón Litio","866","secretaria@pqc.cl","","generico",
 "PQC Consultores en Exponor: calidad y pipeline de proyectos",
 "PQC Consultores participa activamente en el ecosistema minero con proyectos de eficiencia energética, sostenibilidad y eventos como Mujer & Minería 2026.",
 "services","a","a"),
("Precisa Chile","Pabellón Litio","853","contactanos_chile@precision.tech","","ventas",
 "Precisa Chile en Exponor: automatización y leads calificados",
 "Precisa Chile conecta tecnologías de última generación para automatizar la industria minera, con asesoría experta en la integración de soluciones de medición y control.",
 "tech","b","b"),
("Prein Chile Ltda.","Pabellón Yodo","744-745","contactos@preinchile.cl","","ventas",
 "Prein Chile en Exponor: instalaciones eléctricas y pipeline",
 "Prein Chile provee prestaciones industriales eléctricas y mecánicas con oficinas en San Bernardo y Calama, atendiendo directamente a las operaciones mineras del norte.",
 "services","c","c"),
("Prime Integral SpA","Pabellón Hierro","1453","contacto@primeintegral.com","","ventas",
 "Prime Integral en Exponor: proyectos industriales y leads activos",
 "Prime Integral tiene amplia experiencia en proyectos industriales, energéticos, forestales y mineros, con el compromiso como fortaleza diferenciadora en cada entrega.",
 "services","a","d"),
("Procemax SpA","Pabellón Cobalto","1419","info@procemax.com","","ventas",
 "Procemax en Exponor: equipos mineros y pipeline de ventas",
 "Procemax es representante de marcas internacionales de equipos y consultoría para minería, con una amplia gama de soluciones para procesos operacionales complejos.",
 "tech","b","a"),
("Prodalam Minería","Pabellón Yodo","807-808","chillannorte@prodalam.cl","","generico",
 "Prodalam en Exponor: aceros y materiales mineros activos",
 "Prodalam se especializa en aceros, mallas, alambres, cercos, contención y fortificación para la minería, con presencia en todo el norte de Chile para proyectos de gran escala.",
 "parts","c","b"),
("Prodalam Minería","Pabellón Yodo","807-808","iquique@prodalam.cl","","generico",
 "Exponor 2026: Prodalam Iquique y leads bien seguidos",
 "Prodalam tiene cobertura completa en el norte con presencia en Iquique, Antofagasta y Calama, atendiendo los proyectos de acero y materiales de la gran minería chilena.",
 "parts","a","c"),
("Prodalam Minería","Pabellón Yodo","807-808","calama@prodalam.cl","","generico",
 "Prodalam Calama en Exponor: aceros y oportunidades activas",
 "Prodalam Calama atiende directamente a las operaciones mineras de la zona con aceros, mallas y materiales de construcción y contención para los proyectos más grandes del norte.",
 "parts","b","d"),
# ── LOTE 10 ──────────────────────────────────────────────────────────────────
("Prok Conveyor Equipment SpA","Exterior B","38","info@prok.com","","ventas",
 "Prok en Exponor: correas transportadoras y pipeline activo",
 "Prok, filial australiana, es líder en componentes de correas transportadoras y manejo de materiales, con tecnología de optimización para la continuidad operacional de las plantas.",
 "parts","c","a"),
("Prok Conveyor Equipment SpA","Exterior B","38","conveyors.au@prok.com","","generico",
 "Exponor 2026: Prok Australia y seguimiento de oportunidades",
 "Prok opera globalmente con tecnología de referencia en sistemas de transporte de materiales para minería, y su presencia en Exponor conecta con los proyectos más grandes del norte.",
 "parts","a","b"),
("Prok Conveyor Equipment SpA","Exterior B","38","conveyors.id@prok.com","","generico",
 "Prok Conveyor en Exponor: componentes y leads calificados",
 "Prok diseña y fabrica componentes de correa transportadora con estándares industriales internacionales, siendo reconocido por las grandes mineras como proveedor técnico de referencia.",
 "parts","b","c"),
("Promet Soluciones Modulares","Exterior C","92","ventas@promet.cl","","ventas",
 "Promet en Exponor: módulos industriales y pipeline activo",
 "Promet diseña, fabrica y construye soluciones modulares para infraestructura de apoyo y montajes industriales, un servicio esencial para los campamentos y plantas mineras del norte.",
 "constr","c","d"),
("Prominent Chile","Pabellón Cobre","177","prominent-cl@prominent.com","Prominent","personal",
 "Exponor 2026: dosificación química ProMinent y leads activos",
 "ProMinent, filial alemana, provee soluciones de dosificación química de alta precisión para proceso de agua, minería e industria, con el nuevo sensor DULCOEYE LT como última innovación.",
 "tech","a","a"),
("Prored Zona Norte","Pabellón Cobalto","1441","contacto@proredzn.com","","ventas",
 "Prored Zona Norte en Exponor: LTE privada y leads calificados",
 "Prored Zona Norte es experto en redes LTE privadas, IoT Industrial y sistemas de control QHSEC para la gran minería en Tarapacá y Antofagasta, como partner Emerson.",
 "tech","b","b"),
("Provaltec SpA","Pabellón Oro","1180","contactoweb@provaltec.cl","","ventas",
 "Provaltec en Exponor: válvulas industriales y pipeline activo",
 "Provaltec ofrece filtros, válvulas y accesorios industriales de alta calidad para optimizar procesos en minería y sectores exigentes, con enfoque en innovación y confiabilidad.",
 "parts","c","c"),
("Purcell Cerliani SpA","Pabellón Oro","1126","ventas@purcellcerliani.cl","","ventas",
 "Purcell Cerliani en Exponor: hardware minero y leads activos",
 "Purcell Cerliani desarrolla soluciones tecnológicas para minería y grúas, con hardware industrial robusto y automatización para las condiciones más exigentes del norte.",
 "tech","a","d"),
("Radiadores Gómez Ltda.","Exterior A","008-010","contacto@rgomez.cl","","ventas",
 "Radiadores Gómez en Exponor: 50 años y leads que cierran",
 "Radiadores Gómez tiene más de 50 años de experiencia en suministro, reparación y mantención de radiadores e intercambiadores de calor para equipos industriales y mineros.",
 "parts","b","a"),
("Radiadores Gómez Ltda.","Exterior A","008-010","aibacache@rgomez.cl","","generico",
 "Exponor 2026: Radiadores Gómez y seguimiento post-feria",
 "Radiadores Gómez atiende a la gran minería con la experiencia técnica más larga en transferencia de calor industrial, siendo proveedor de referencia para los equipos de mantención.",
 "parts","c","b"),
("Raico S.A.","Pabellón Molibdeno","1298-1327","info@raico.cl","","ventas",
 "Raico en Exponor: maquinaria forestal y pipeline de ventas",
 "Raico vende y arrienda maquinaria para movimiento de tierra y manejo de material, con repuestos y servicio técnico en terreno para minimizar tiempos de detención.",
 "parts","a","c"),
("Refamaq Industrial Ltda.","Pabellón Litio","948","contacto@refamaq.cl","","ventas",
 "Refamaq en Exponor: válvulas industriales y leads activos",
 "Refamaq ofrece válvulas industriales y sistemas de automatización de alta calidad para el sector minero, con enfoque en la confiabilidad de los procesos hidráulicos y de control.",
 "parts","b","d"),
("Resolutions - Soluciones Integrales de Comunicación","Pabellón Yodo","705","ventas@resolutions.cl","","ventas",
 "Resolutions en Exponor: comunicaciones y pipeline activo",
 "Resolutions provee soluciones tecnológicas en comunicación, seguridad y operación continua, trabajando con marcas líderes para mantener conectada la operación minera.",
 "tech","c","a"),
("Rivet Ltda.","Pabellón Plata","557-587","info@rivet.cl","","ventas",
 "Rivet en Exponor: transporte de minerales y leads activos",
 "Rivet provee productos para transporte y clasificación de minerales, con soluciones de protección de superficies y servicios técnicos para plantas de procesamiento.",
 "parts","a","b"),
("Rocktrain SpA","Pabellón Plata","624","contacto@rocktrain.cl","","ventas",
 "Rocktrain en Exponor 2026: ¿tienen el sistema de leads listo?",
 "Rocktrain atiende el mercado minero con soluciones técnicas especializadas para las operaciones del norte, con enfoque en confiabilidad y continuidad operacional.",
 "services","b","c"),
("Rodamendez Ltda.","Pabellón Plata","346-402","contacto@rodamendez.cl","","ventas",
 "Rodamendez en Exponor: rodamientos y leads bien seguidos",
 "Rodamendez es líder en rodamientos, chumaceras, cadenas, correas y accesorios de transmisión, con más de 50 años de presencia en todo Chile para el sector industrial y minero.",
 "parts","c","d"),
("RPI Productos Industriales S.A.","Exterior E","131","ventas@rpichile.cl","","ventas",
 "RPI en Exponor: productos industriales y pipeline activo",
 "RPI Productos Industriales ofrece garantía de calidad y excelente atención con marcas reconocidas a nivel mundial, distribuyendo productos técnicos para la industria minera.",
 "parts","a","a"),
# ── LOTE 11 ──────────────────────────────────────────────────────────────────
("RUD + SpanSet","Pabellón Cobre","84","administracion@rud.com","","generico",
 "RUD en Exponor: cadenas de izaje y leads calificados",
 "RUD Chile, filial de la empresa alemana, ofrece soluciones personalizadas en cadenas, eslingas y sistemas de izaje y amarre de clase mundial para la gran minería.",
 "parts","b","b"),
("Sapri SpA","Pabellón Litio","985-990","alvaro.romero@sapri.cl","Alvaro","personal",
 "Alvaro, Exponor 2026: puesta en marcha eléctrica y leads activos",
 "Sapri ofrece servicios eléctricos especializados para la puesta en marcha de plantas industriales, con asesoría profesional y conocimiento directo de los proyectos mineros del norte.",
 "services","c","c"),
("Sattel Chile","Pabellón Yodo","762","contacto@sattelchile.cl","","ventas",
 "Sattel Chile en Exponor: telecomunicaciones y pipeline activo",
 "Sattel Chile diseña e implementa soluciones tecnológicas para la minería nacional e internacional, con enfoque en telecomunicaciones satelitales para faenas remotas.",
 "tech","a","d"),
("Scancontrols Ing. Ltda.","Pabellón Cobalto","1342","infonorte@scancontrols.cl","","ventas",
 "Scancontrols en Exponor: válvulas y 25.000 reparaciones",
 "Scancontrols es líder nacional en ventas, reparación y mantención de válvulas de control, con más de 25.000 equipos reparados y cero devoluciones en garantía.",
 "parts","b","a"),
("Schussler S.A.","Pabellón Yodo","746","ventas@schussler.cl","","ventas",
 "Schussler en Exponor: ingeniería nacional y leads activos",
 "Schussler es empresa nacional de productos de ingeniería y arriendo de maquinaria para la industria, con décadas de presencia en proyectos del norte minero.",
 "parts","c","b"),
("Segin SpA","Pabellón Litio","824","ventas@segin.cl","","ventas",
 "Segin en Exponor: EPP minero y compradores bien seguidos",
 "Segin provee EPP y seguridad industrial para la minería, con catálogo en línea y presencia directa en el Pabellón Litio de Exponor para atender a los compradores del sector.",
 "epp","a","c"),
("Segin SpA","Pabellón Litio","824","mzanartu@segin.cl","","generico",
 "Exponor 2026: Segin EPP y pipeline de seguridad industrial",
 "Segin tiene el catálogo completo en EPP y seguridad para minería, con presencia activa en Exponor para conectar con los responsables de seguridad de las grandes operaciones.",
 "epp","b","d"),
("Segin SpA","Pabellón Litio","824","pmoreno@segin.cl","","generico",
 "Segin en Exponor 2026: ¿tienen su sistema de leads listo?",
 "Segin atiende a la gran minería del norte con equipos de protección personal y seguridad industrial, siendo un proveedor de referencia en el Pabellón Litio de Exponor.",
 "epp","c","a"),
("Segusa Chile SpA","Pabellón Plata","618","ventas5@segusachile.cl","","ventas",
 "Segusa en Exponor: 25 años de EPP y leads calificados",
 "Segusa Chile tiene más de 25 años como empresa especializada en EPP y seguridad industrial, con sólida trayectoria de marca y presencia directa en el mercado minero.",
 "epp","a","b"),
("Segusa Chile SpA","Pabellón Plata","618","ventas@segusachile.cl","","ventas",
 "Exponor 2026: seguridad Segusa y pipeline de compradores",
 "Segusa Chile opera con sólida presencia en EPP y seguridad industrial, siendo proveedor reconocido de las grandes mineras que exigen estándares de calidad en cada entrega.",
 "epp","b","c"),
("Segusa Chile SpA","Pabellón Plata","618","gerenciacomercial@segusachile.cl","","generico",
 "Gerencia Segusa: Exponor 2026 y sistema de seguimiento",
 "Segusa Chile tiene 25 años de posicionamiento en seguridad industrial minera y Exponor 2026 es la feria más importante del año para consolidar ese liderazgo con nuevos clientes.",
 "epp","c","d"),
("Servicios LyG","Pabellón Oro","1038","contacto@servicioslyg.cl","","ventas",
 "Servicios LyG en Exponor: abastecimiento y leads activos",
 "Servicios LyG es empresa de abastecimiento minero e industrial especializada en EPP y ferretería, con enfoque directo en el servicio a las operaciones del norte.",
 "epp","a","a"),
("Sitrack Chile","Pabellón Hierro","1460","clientes.ar@sitrack.com","","generico",
 "Sitrack en Exponor: tracking de flota y leads calificados",
 "Sitrack Chile provee soluciones de telemetría y tracking de flota minera, tecnología que permite monitorear equipos en tiempo real y optimizar la operación.",
 "tech","b","b"),
("Sitrack Chile","Pabellón Hierro","1460","clientes.uy@sitrack.com","","generico",
 "Exponor 2026: Sitrack telemetría y seguimiento post-feria",
 "Sitrack ofrece soluciones inteligentes de seguimiento de flota para la minería latinoamericana, con presencia en Chile, Uruguay, Argentina y Perú.",
 "tech","c","c"),
("Sitrack Chile","Pabellón Hierro","1460","clientes.pe@sitrack.com","","generico",
 "Sitrack en Exponor 2026: ¿tienen su pipeline de leads listo?",
 "Sitrack provee tecnología de seguimiento de flota para las operaciones mineras más grandes de Sudamérica, y Exponor es donde sus prospectos más importantes van a estar.",
 "tech","a","d"),
("Sociedad Comercial Socoval SpA","Exterior A","011","contacto@coval.cl","","ventas",
 "Coval en Exponor: financiamiento digital y leads activos",
 "Coval ofrece servicios financieros 100% digitales para empresas, incluyendo factoring, leasing y capital de trabajo para los proveedores del sector minero que necesitan liquidez.",
 "services","b","a"),
# ── LOTE 12 ──────────────────────────────────────────────────────────────────
("Soltex Chile S.A.","Pabellón Cobre","245","rcereceda@soltex.cl","","generico",
 "Soltex en Exponor: geosintéticos y pipeline de proyectos",
 "Soltex comercializa geosintéticos y textiles industriales para la minería, con aplicaciones en impermeabilización, drenaje y contención para los proyectos más exigentes del norte.",
 "parts","c","b"),
("Soltex Chile S.A.","Pabellón Cobre","245","cpadilla@soltex.cl","","generico",
 "Exponor 2026: Soltex geomembranas y leads calificados",
 "Soltex provee geomembranas y textiles técnicos para la minería, productos de alta especialización que los ingenieros de proyectos buscan para pilas de lixiviación y tranques.",
 "parts","a","c"),
("Soltex Chile S.A.","Pabellón Cobre","245","central@soltex.cl","","generico",
 "Soltex Chile en Exponor 2026: textiles mineros y seguimiento",
 "Soltex tiene el portafolio más completo en geosintéticos y textiles técnicos para minería, con soluciones reconocidas en los proyectos de mayor escala del norte.",
 "parts","b","d"),
("Sotrafa S.A.","Pabellón Plata","483","info@sotrafa.com","","ventas",
 "Sotrafa en Exponor: geomembranas y pipeline activo",
 "Sotrafa, filial española, produce geomembranas y plásticos con amplia gama de productos para impermeabilización en minería, material crítico para las pilas de lixiviación.",
 "services","c","a"),
("Southblu Grupo Pimasa","Pabellón Cobre","224","contacto@southblu.cl","","ventas",
 "Southblu en Exponor: remediación ambiental y leads activos",
 "Southblu del Grupo Pimasa tiene más de 30 años en servicios y tecnologías de modelación, monitoreo y remoción de contaminantes, apoyando a la minería en sus compromisos ambientales.",
 "services","a","b"),
("SSAB Chile","Pabellón Oro","1118","contactchile@ssab.com","","ventas",
 "SSAB en Exponor: acero de alta resistencia y pipeline activo",
 "SSAB Chile, filial sueca, ofrece aceros de alta resistencia para las aplicaciones más exigentes de la minería, con portafolio técnico que reduce peso y aumenta la vida útil.",
 "parts","b","c"),
("SSAB Chile","Pabellón Oro","1118","info.turkiye@ssab.com","","ventas",
 "Exponor 2026: SSAB aceros y seguimiento de oportunidades",
 "SSAB opera globalmente con aceros de alta resistencia para minería y construcción, siendo reconocido por los ingenieros de proyectos que buscan optimizar el diseño estructural.",
 "parts","c","d"),
("SSAB Chile","Pabellón Oro","1118","info.pt@ssab.com","","ventas",
 "SSAB en Exponor 2026: aceros nórdicos y leads calificados",
 "SSAB fabrica aceros especiales que hacen posible estructuras más livianas y duraderas en la minería, con presencia global y soporte técnico directo en Chile.",
 "parts","a","a"),
("Statkraft Chile","Pabellón Litio","1012","contacto@statkraft.com","","ventas",
 "Statkraft en Exponor: renovables para minería y pipeline",
 "Statkraft, el mayor generador de energía renovable de Europa, tiene en Chile proyectos hidroeléctricos, eólicos y solares que conectan directamente con la demanda de las grandes mineras.",
 "services","b","b"),
("Stec SpA","Pabellón Yodo","659","contacto@stecindustrial.cl","","ventas",
 "Stec en Exponor: mantenimiento industrial y leads activos",
 "Stec provee servicios de mantenimiento industrial y suministro de equipamiento de alta tecnología para sectores industriales y mineros del norte de Chile.",
 "services","c","c"),
("Steelmaster Ltda","Pabellón Cobalto","1366","info@steelmasterusa.com","","ventas",
 "Steelmaster en Exponor: estructuras de acero y pipeline",
 "Steelmaster diseña y fabrica estructuras de acero prediseñadas para proyectos industriales y mineros, con soluciones modulares de alta resistencia para las condiciones del norte.",
 "constr","a","d"),
("Sumin Chile Spa.","Exterior A","001","ventas@suminchile.cl","","ventas",
 "Sumin Chile en Exponor: suministros mineros y leads activos",
 "Sumin Chile provee servicios para la minería y sector industrial con innovación y calidad duradera, siendo uno de los primeros expositores al ingresar a Exponor 2026.",
 "parts","b","a"),
("Swastic Drilling Co & Maquinet SpA","Pabellón Molibdeno","1252-1253","administracion@maquinet-spa.cl","","generico",
 "MaquiNet en Exponor: perforación y pipeline de ventas",
 "MaquiNet Chile se dedica a la importación directa de equipos de perforación, siendo el contacto local para tecnología de drilling de origen internacional en el mercado minero.",
 "parts","c","b"),
("Tasco Chile Ltda.","Exterior E","117","ventasweb@tascochile.cl","","ventas",
 "Tasco en Exponor: suministros mineros y compradores activos",
 "Tasco Chile provee suministros para la minería con un catálogo de productos de alta demanda y venta en línea, sirviendo a las operaciones del norte con agilidad y stock disponible.",
 "parts","a","c"),
("Tecic SpA","Exterior B","056-057","ventas@tecic.cl","","ventas",
 "Tecic en Exponor: tableros eléctricos y leads calificados",
 "Tecic se especializa en ingeniería e integración de tableros y salas eléctricas para la industria, un servicio técnico de alta especialización para proyectos mineros.",
 "tech","b","d"),
("Teck Resources Chile","Exterior B","053A","info@miningsurplus.com","","ventas",
 "Exponor 2026: Teck Resources y seguimiento de oportunidades",
 "Teck Resources, corporación canadiense, opera QB2 y Carmen de Andacollo en Chile, siendo una de las mayores productoras de cobre y referente del sector que estará en Exponor.",
 "services","c","a"),
("Teck Resources Chile","Exterior B","053A","sales@irm.com","","ventas",
 "Teck en Exponor 2026: minería responsable y pipeline activo",
 "Teck Resources lleva al sector minero las más altas prácticas de operación responsable, y su presencia en Exponor genera interés de proveedores especializados y socios estratégicos.",
 "services","a","b"),
("Teck Resources Chile","Exterior B","053A","info@cesl.com","","ventas",
 "Exponor 2026: Teck CESL y contactos bien gestionados",
 "Teck Resources opera en Chile con proyectos de cobre de escala mundial, y CESL representa su división de tecnologías de procesamiento con aplicaciones en la gran minería.",
 "services","b","c"),
# ── LOTE 13 ──────────────────────────────────────────────────────────────────
("Tectramin Chile SpA","Pabellón Litio","979","ventas@tectramin.com","","ventas",
 "Tectramin en Exponor: detección de fugas y leads activos",
 "Tectramin identifica fugas en sistemas impermeabilizados usando el campo eléctrico natural del terreno, tecnología que contribuye directamente a la rentabilidad de las operaciones mineras.",
 "tech","c","d"),
("Teknica Chile","Exterior E","122-127","teknicachile@teknica.cl","","generico",
 "Teknica en Exponor: power quality y pipeline de proyectos",
 "Teknica diseña soluciones en power quality, UPS, distribución de energía, clima de precisión y extinción de incendios para la infraestructura crítica de las operaciones mineras.",
 "tech","a","a"),
("Teknica Chile","Exterior E","122-127","teknicanorte@teknica.cl","","generico",
 "Exponor 2026: Teknica Norte y seguimiento de oportunidades",
 "Teknica Norte atiende a la gran minería del norte con soluciones de continuidad operacional en UPS y power quality, servicios esenciales para las plantas de proceso.",
 "tech","b","b"),
("Tiar Ltda. - Cidra","Pabellón Yodo","752","tiar@tiar.cl","","generico",
 "Tiar-Cidra en Exponor: medición de flujo y leads activos",
 "Tiar representa marcas de clase mundial en medición de flujo como KROHNE, Bronkhorst y Sitelab, con expertise técnico para las variables de proceso más críticas de la minería.",
 "tech","c","c"),
("TMC Transformers SpA","Pabellón Litio","848","marketing@tmctransformers.com","","generico",
 "TMC Transformers en Exponor: transformadores y pipeline activo",
 "TMC se especializa en producción de transformadores secos y de resina colada para diferentes aplicaciones industriales, soluciones de alta confiabilidad para la infraestructura minera.",
 "tech","a","d"),
("TMC Transformers SpA","Pabellón Litio","848","recruiting@tmctransformers.com","","generico",
 "Exponor 2026: TMC Transformers y talento para el stand",
 "TMC Transformers opera con transformadores de alta confiabilidad para minería e industria, y en Exponor van a necesitar el equipo y el sistema correcto para capturar cada oportunidad.",
 "tech","b","a"),
("Track Rail SpA","Pabellón Molibdeno","1305","contacto@trackrail.cl","","ventas",
 "Track Rail en Exponor: infraestructura ferroviaria y leads activos",
 "TrackRail se enfoca en mantenimiento e infraestructura ferroviaria para el segmento industrial y minero, un servicio técnico especializado con alta demanda en operaciones de gran escala.",
 "services","c","b"),
("Transducto S.A.","Pabellón Cobalto","1352","info@transducto.com","","ventas",
 "Transducto en Exponor: DOM-TEC y recuperación de metales",
 "Transducto desarrolla DOM-TEC, tecnología sustentable para recuperar cobre, oro y plata desde relaves y soluciones industriales, con impacto directo en la rentabilidad minera.",
 "tech","a","c"),
("Transformadores CH S.A.","Pabellón Oro","1198","zonanorte@transformadores.cl","","generico",
 "Transformadores CH Norte en Exponor: soluciones y leads",
 "Transformadores CH es especialista en fabricación a medida de transformadores, pad mounted y subestaciones eléctricas, con presencia directa en la zona norte para proyectos mineros.",
 "tech","b","d"),
("Transformadores CH S.A.","Pabellón Oro","1198","ventas@transformadores.cl","","ventas",
 "Transformadores CH en Exponor: subestaciones y pipeline activo",
 "Transformadores CH fabrica transformadores y subestaciones a medida para los proyectos de electrificación más exigentes de la minería chilena, con cobertura nacional.",
 "tech","c","a"),
("Transformadores CH S.A.","Pabellón Oro","1198","ch@transformadores.cl","","generico",
 "Exponor 2026: Transformadores CH y seguimiento de oportunidades",
 "Transformadores CH opera como especialista técnico en el diseño y fabricación de transformadores para la gran minería, con soluciones a medida reconocidas en el mercado chileno.",
 "tech","a","b"),
("Transformadores Tusan S.A.","Pabellón Litio","838-840","ventas@tusan.cl","","ventas",
 "Tusan en Exponor: transformadores y pipeline de proyectos",
 "Tusan transforma la energía con transformadores eléctricos para un futuro más amigable con el medio ambiente, con soluciones técnicas para los proyectos de electrificación minera.",
 "tech","b","c"),
("Transportes Bello e Hijos Ltda.","Exterior E","141-142","info@transportesbello.com","","ventas",
 "Transportes Bello en Exponor: logística y leads activos",
 "Transportes Bello tiene más de medio siglo como socio en logística y transporte de carga, con soluciones sostenibles para la cadena de suministro de los proyectos mineros del norte.",
 "services","c","d"),
("Transportes Santa Eva","Pabellón Molibdeno","1214","contacto@transe.cl","","ventas",
 "Santa Eva en Exponor: sobredimensionado y leads calificados",
 "Transportes Santa Eva es especialista en transporte de sobredimensionado por carretera, moviendo las cargas más exigentes del mercado minero con precisión y seguridad.",
 "services","a","a"),
("TTPM S.A.","Exterior B","55","ttpm@ttpm.cl","","generico",
 "TTPM en Exponor: transmisión de potencia y pipeline activo",
 "TTPM provee soluciones industriales en transmisión de potencia mecánica, movilidad eléctrica, izaje, iluminación y bombeo de fluidos para el norte minero.",
 "parts","b","b"),
("UNIDELTA SpA","Pabellón Cobre","139B","unidelta@unidelta.com","","generico",
 "Unidelta en Exponor: tuberías italianas y leads calificados",
 "Unidelta, filial italiana con 50 años de historia, produce tuberías y fittings de polietileno para agua, gas e instalaciones industriales, con presencia en proyectos mineros.",
 "parts","c","c"),
("Ventas Técnicas Ltda.","Pabellón Yodo","684","contacto@ventastecnicas.cl","","ventas",
 "Ventas Técnicas en Exponor: call center y leads bien seguidos",
 "Ventas Técnicas es experta en call center y campañas de ventas B2B con más de 20 años, un servicio que los proveedores mineros usan para dar seguimiento sistemático post-feria.",
 "services","a","d"),
("Ventas Técnicas Ltda.","Pabellón Yodo","684","contacto@ventastecnicas.pe","","ventas",
 "Exponor 2026: Ventas Técnicas Perú y pipeline activo",
 "Ventas Técnicas opera en Perú y Chile con equipos especializados en ventas B2B, un servicio que los proveedores mineros que expanden operaciones en el norte necesitan.",
 "services","b","a"),
("Veto y Cía.","Pabellón Yodo","660","ventas@veto.cl","","ventas",
 "Veto y Cía. en Exponor: instrumentación y leads calificados",
 "Veto y Cía. comercializa instrumentación de nivel, flujo, presión y temperatura, además de automatización eléctrica, con catálogo completo para la instrumentación minera.",
 "tech","c","b"),
("Von Unger Representaciones SpA","Pabellón Cobalto","1442","vonunger@vonunger.cl","","generico",
 "Von Unger en Exponor: HDPE y pipeline de proyectos activos",
 "Von Unger comercializa soldadoras de termofusión, extrudoras de aporte y fittings de HDPE y electrofusión, componentes críticos para el tendido de tuberías en la minería del norte.",
 "parts","a","c"),
("Wika Chile","Pabellón Cobre","4","info@wika.cl","","ventas",
 "WIKA en Exponor: sensores industriales y leads bien seguidos",
 "WIKA es 'Smart in sensing', con soluciones inteligentes en instrumentación de presión, temperatura y nivel para los procesos más críticos de la gran minería.",
 "tech","b","d"),
("XCMG Chile","Exterior E","138-139","fwb@xcmg.com","","generico",
 "XCMG en Exponor: maquinaria china y pipeline de ventas",
 "XCMG, tercer fabricante de maquinaria de construcción del mundo y marca Fortune 500, ofrece grúas, excavadoras, cargadores y plataformas para las operaciones mineras.",
 "parts","c","a"),
("Yprotec SpA","Pabellón Oro","1089","contacto@yapur.cl","","ventas",
 "Yprotec Graco en Exponor: dosificación y leads activos",
 "Yprotec es distribuidor oficial de GRACO en Chile, con soporte técnico y comercial a lo largo del país para los sistemas de pulverización y dosificación de fluidos en minería.",
 "parts","a","b"),
("Yura Chile","Pabellón Plata","574-575","ventas.arica@yura.cl","","ventas",
 "Yura Chile en Exponor: cemento y pipeline de construcción",
 "Cemento Yura Chile, con más de 52 años y parte del Grupo Gloria de Perú, provee cemento de alta calidad para construcción e infraestructura minera en el norte.",
 "parts","b","c"),
("Yura Chile","Pabellón Plata","574-575","ventas.iquique@yura.cl","","ventas",
 "Exponor 2026: Yura Iquique y seguimiento de compradores",
 "Yura Chile atiende al norte desde Iquique con cemento de alta calidad para los proyectos de construcción e infraestructura que la gran minería requiere.",
 "parts","c","d"),
("Yura Chile","Pabellón Plata","574-575","logistica.arica@yura.cl","","generico",
 "Yura Logística en Exponor: cemento y operación bien seguida",
 "Yura Chile gestiona la logística de cemento para el norte desde Arica, asegurando suministro oportuno para los proyectos de construcción minera más exigentes.",
 "parts","a","a"),
("Zamine Service Chile SpA","Pabellón Hierro","1464","info@zamineservice.com","","ventas",
 "Zamine en Exponor: servicio técnico minero y leads activos",
 "Zamine Service Chile provee servicio técnico especializado para equipos de minería subterránea y de superficie, con representación de marcas de reconocimiento internacional.",
 "parts","b","b"),
]

fieldnames = ['empresa','pabellon','stand','email','nombre_contacto','asunto','cuerpo_completo']

with open(OUTPUT, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
    writer.writeheader()
    for row in ROWS:
        empresa, pabellon, stand, email, nombre, tipo, asunto, l1, l2k, l3k, l4k = row
        generated = build(empresa, tipo, nombre, asunto, l1, l2k, l3k, l4k)
        writer.writerow({
            'empresa': empresa,
            'pabellon': pabellon,
            'stand': stand,
            'email': email,
            'nombre_contacto': nombre,
            'asunto': generated['asunto'],
            'cuerpo_completo': generated['cuerpo_completo'],
        })

print(f"✅ {len(ROWS)} emails generados → {OUTPUT}")
